apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
data:
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0
    mysql_native_password=ON
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 200
    shared_buffers = 256MB
    log_timezone = 'UTC'
    timezone = 'UTC'
  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             0.0.0.0/0               md5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
data:
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_LOG_RETENTION_HOURS: "168"
